# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SDKGithubServices' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SDKGithubServices
   pod 'Alamofire'

  target 'SDKGithubServicesTests' do
    # Pods for testing
  end

end

target 'SDKGithubServicesSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SDKGithubServicesSample

end
